version: '3.8'

services:
  auth-service:
    build: .
    container_name: hakaton-auth
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
